#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=demo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=logs/demo_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate lean-reinforcement

# Source environment variables
set -a
source $HOME/leandojo/.env
set +a

# CRITICAL: Prevent any redundant tracing or building
export LOAD_USED_PACKAGES_ONLY=1

cd $HOME/leandojo/scripts

srun python3 demo-lean4.py